services:
  app:
    image: test_task_image
    build: 
        context: ./app
        target: builder
    container_name: app_container
    depends_on:
        db:
            condition: service_healthy
    environment:
        PORT: 8000
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
        SPRING_DATASOURCE_USERNAME: ${DB_USER}
        SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
    ports:
        - '8000:8000'
  db:
    environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASS}
        POSTGRES_DB: ${DB_NAME}
    build:
      context: .
      dockerfile: ./db.Dockerfile
    container_name: postgres_db_container
    ports:
        - "5432:5432"
    restart: always
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
        interval: 10s
        timeout: 5s
        retries: 5

  pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
        ports:
            - "5050:80"
        restart: always